language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
 - composer self-update
 - composer install

script:
 - mkdir -p build/logs
 - vendor/bin/codecept run --coverage-xml=./coverage.clover

after_success:
  - bash <(curl -s https://codecov.io/bash)
