language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
 - composer self-update
 - composer install  --no-interaction

script:
 - vendor/bin/codecept run unit --coverage --coverage-xml --coverage-html --no-colors

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
